### ISSUE TITLE
New View

### ISSUE THREAD

**Issue by jamierocks** [LapisBlue/Lapitar#3]
I think it would be really cool if you had a view similar to @RyanTheAllmighty's avatar.
![image](https://cloud.githubusercontent.com/assets/5103549/5550620/075b97d8-8ba2-11e4-9a33-b5f7b46e7dbf.png)

**Comment by Minecrell** [comment]
Feel free to report this on the Visage issue tracker again if you still want this. Thanks!

**Comment by jamierocks** [comment]
u mad?
