### ISSUE TITLE
Is there a way to donate?

### ISSUE THREAD

**Issue by divad** [LapisBlue/Lapitar#5]
Add a PayPal donate button so we can donate to help you out :) I'd love to use this app in production on our network but its not fair for it to be free!

**Comment by AesenV** [comment]
(woo, late reply!)
Lapitar isn't exactly a good idea to use in production at the moment, as it's running on a really slow cloud box with no guaranteed uptime or anything.

I'm working on a hardware accelerated high-uptime service for using in production; I originally started this project for exactly this purpose. Once this alternate service comes out, it will be linked to my Patreon, so you could help support the hosting cost through that.

I'm not sure if Minecrell has a Patreon, but he's who is currently hosting Lapitar, and managed the Go/C port.

**Comment by Minecrell** [comment]
@AesenV just to clear this up, the current server is neither really slow nor is it down very often. I wouldn't call it extremely performant, but CloudFlare caches most things efficiently already so it has a definitely acceptable performance. The server itself has guaranteed uptime of 99.6% (excluding my own maintenance) but in the last time it had probably an uptime of over 99.9%

A hardware accelerated instance would be of cause faster, but it's not the case that it's currently completely unusable.

**Comment by AesenV** [comment]
You have explicitly put a banner up on the Lapitar site saying not to use
it in production.
CloudFlare does cache, yes, but for an initial load it takes a long time
due to CPU rendering on a virtual, and rather slow, CPU.

I'm also not implying the box is down often, just that it has no uptime
predictability, something you explicitly say in your banner.

**Comment by Minecrell** [comment]
@AesenV That's essentially something older when Lapitar was in active development, but I haven't made an changes for a longer time which is why there was no downtime.

**Comment by AesenV** [comment]
@divad The 2.0 rewrite is now happening at https://github.com/AesenV/Visage - keep an eye on it so you know when it's done and you can switch over.
