### ISSUE TITLE
Cannot use hardware acceleration

### ISSUE THREAD

**Issue by AesenV** [LapisBlue/Lapitar#6]
Not entirely sure how you would do this in C, but I may make a new branch based on `research` for doing accelerated rendering with a server.

~~Hardware accel is the only truly viable way to do perspective rendering dynamically like we are on a large scale; unless there's some way to "cache" the polys and only need to project the textures? It may be worth looking into newer versions of the GL spec for this.~~

That's basically exactly what VBOs are. Working on a "Lapitar2" that uses VBOs among other things.

**Comment by Minecrell** [comment]
I think it should be also possible to use C++ together with Go if that would help for the newer GL stuff.

**Comment by AesenV** [comment]
It really won't. Java isn't inefficient, the research branch was just inefficient. I'm working on a rewrite in the `next` branch based on Jetty and VBOs.

**Comment by Minecrell** [comment]
Rewriting the complete (web) server would be kinda wasted time, as the Go version has most things working already.

**Comment by AesenV** [comment]
Yes, but moving to Java encourages more contributions, as the Minecraft world has more Java developers than Go/C, I'll be able to work directly on the codebase again, and we'll have a full flexible system.

Also, the server part of Lapitar is extremely simple. The renderer is the issue, and I have to rewrite the renderer to use VBOs anyway.

**Comment by Minecrell** [comment]
@AesenV You forget that I've spent tons of hours into the Go version of this, which is the only reason why I'm kinda against this. Also, in terms of web servers, I wouldn't say Java is really known to be performant within the Minecraft community (especially due to bad experience with the Minecraft server which is just slow because it is written in a single threaded way.

**Comment by AesenV** [comment]
Java does have a bad reputation, but that is thanks to Mojang's poor code and single-threaded-ness (as you already mentioned). That also doesn't change the fact there's more Java developers.

I get that you spent a bunch of time on the Go port, but you are basically the only one who can maintain it. I can barely touch the C, I can't code in Go, basically everyone you've mentioned Go to responds in a "meh, it's interesting but no" way. In addition, the existing renderer is based on OpenGL 1.1, which is an *ancient* standard, and it doesn't even use display lists. The new renderer, while still based on an older version of OpenGL (1.5), will be a lot faster since it will leverage VBOs. I'm also building it on top of a master/slave model to make it more viable for use in a production setting, which would require a full rework of the web server anyway.

Do you really want to port a bunch of GL code into C again, rewrite the Go server, port a bunch of Java master/slave management code into Go, and learn how to use RabbitMQ?

I can also add some features that have been waited for for a while; like the query strings to change the rotation and to turn on and off certain body layers. I've also devised a new, much more efficient, and better looking, way to do the shadows now via GL_SMOOTH.

All in all, the rewrite is shaping up to be *very* different from the current version.


The main reason for this rewrite is to move this off of your hardware and onto mine, and get it working with acceleration so some people can actually use this thing, instead of it being *yet another cool toy*.

**Comment by AesenV** [comment]
This issue is being addressed in my rewrite at https://github.com/AesenV/Visage
