### ISSUE TITLE
Incorrect skin shown for user.

### ISSUE THREAD

**Issue by khazhyk** [LapisBlue/Lapitar#7]
![https://lapitar.lapis.blue/skin/khazhyk](https://lapitar.lapis.blue/skin/khazhyk)
Should be 
![http://textures.minecraft.net/texture/d3a35354d79e4b611f68ebf3588aec21a5dcf25e538e2a83b754f3f6d5e5169](http://textures.minecraft.net/texture/d3a35354d79e4b611f68ebf3588aec21a5dcf25e538e2a83b754f3f6d5e5169)

https://lapitar.lapis.blue/skin/khazhyk

**Comment by jamierocks** [comment]
21:10 Aesen:
minecrell: any idea why this is happening? https://github.com/LapisBlue/Lapitar/issues/7
21:10 Aesen:
I've checked the relevant Mojang API calls and they're correct
21:10 minecrell:
Lapitar's current cache is kinda eww
21:10 minecrell:
It's working fine but I never finished it
21:10 minecrell:
It's caching skins infinitely
21:10 Aesen:
ah

**Comment by Minecrell** [comment]
`[22:27:33] <@minecrell> The temporary workaround would be to restart Lapitar`
Fixed.
