### ISSUE TITLE
502 in https://lapitar.lapis.blue/portrait/ and more

### ISSUE THREAD

**Issue by RubeVi** [LapisBlue/Lapitar#8]

**Comment by AesenV** [comment]
It appears Lapitar is down; to my knowledge, Minecrell has officially deprecated Lapitar in favor of [Visage](/AesenV/Visage), which has a hosted version at https://visage.gameminers.com/

The API is identical, and the renders are GPU-backed, with slightly different lighting as a result.

Migration concerns:

 - The 'player' endpoint's size argument is now height, not width, and is capped at 512 like the other endpoints
 - The 'face' endpoint now includes the helm
 - The 'helm' endpoint has been removed

/cc @Minecrell - correct me if I'm wrong

**Comment by Minecrell** [comment]
Probably forgot to start Lapitar again after my server went down doe some minutes yesterday. Aesen is mostly right, though.

**Comment by Minecrell** [comment]
Fixed this more or less, all requests will be redirected to Visage now.
