### ISSUE TITLE
Support for custom renders

### ISSUE THREAD

**Issue by KieronWiltshire** [LapisBlue/Lapitar#9]
If you take a look at the hive's player page, they are able to generate a custom user model.
Here is my page for example: http://hivemc.com/player/kraz__ 

Could you possibly allow the ability to specify a custom render where perhaps I can define a stance in JSON, and have this generate, perhaps allow the JSON to be submitted along with the request?

**Comment by unascribed** [comment]
This will require a pretty major overhaul to the rendering engine, but it is a planned feature.

Also, this issue belongs in [the Visage issue tracker](/AesenV/Visage/issues), as Lapitar has been superseded by it.

**Comment by Minecrell** [comment]
Please move this issue into the Visage issue tracker. Thanks!
